nodeLinker: node-modules

packageExtensions:
  unplugin-vue-router@*:
    dependencies:
      "@vue/compiler-sfc": "*"

plugins:
  - checksum: 006d0325e832b7267fa88084a62d319de313ca2541dca62f8fea3125f095a4cc1b8791897f1d803d38179a972aa2152533d11525e463fb8073ca358ee8601f44
    path: .yarn/plugins/@yarnpkg/plugin-spdx.cjs
    spec: "https://raw.githubusercontent.com/spdx/yarn-plugin-spdx/main/bundles/@yarnpkg/plugin-spdx.js"
